# Generated by Django 5.1.3 on 2024-12-11 09:11

import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0018_alter_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Car Model', 'verbose_name_plural': 'Car Models'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Order Line', 'verbose_name_plural': 'Order Lines'},
        ),
        migrations.AlterModelOptions(
            name='orderreview',
            options={'ordering': ['-date_created'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='profilis',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(help_text='Select the car model', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.carmodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='customer',
            field=models.CharField(help_text='Enter the customer name or company', max_length=100, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Enter the car model description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(help_text='Enter the car license plate', max_length=20, verbose_name='License Plate'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(help_text='Enter the car VIN code', max_length=50, verbose_name='VIN Code'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='make',
            field=models.CharField(help_text='Enter the car make', max_length=100, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(help_text='Enter the car model', max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(help_text='Select the car for the order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Enter the order date', null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Enter the car model description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique order ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', help_text='Select the order status', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(help_text='Select the order to which the line belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.order'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Enter the quantity of performed services', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='service',
            field=models.ForeignKey(help_text='Select the performed service', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.service'),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Enter the service name (e.g., Oil Change)', max_length=100, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the service price (e.g., 50.00)', max_digits=10, verbose_name='Price'),
        ),
    ]
